# Generated by Django 2.2.10 on 2021-06-17 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210614_1832'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incidencia',
            old_name='severidad',
            new_name='grado',
        ),
        migrations.RenameField(
            model_name='incidencia',
            old_name='responsable',
            new_name='responsables',
        ),
        migrations.RenameField(
            model_name='incidencia',
            old_name='tipoSolicitud',
            new_name='tipo',
        ),
        migrations.RenameField(
            model_name='incidencia',
            old_name='tituloIncidente',
            new_name='titulo',
        ),
    ]
