# Generated by Django 2.2.10 on 2021-06-21 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210617_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='horasTrabajo',
            field=models.TimeField(null=True),
        ),
    ]
