# Generated by Django 2.2.10 on 2021-07-12 21:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0004_auto_20210621_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='miembros',
        ),
        migrations.AddField(
            model_name='equipo',
            name='miembros',
            field=models.ManyToManyField(related_name='equipo_miembros', to=settings.AUTH_USER_MODEL),
        ),
    ]
