# Generated by Django 2.2.10 on 2021-07-12 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210712_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='horasTrabajo',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='incidencia',
            name='horasEstimadas',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
    ]
