# Generated by Django 2.2.10 on 2021-07-13 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210712_1625'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incidencia',
            options={'ordering': ('fechaCreacion',)},
        ),
    ]
