# Generated by Django 2.2.10 on 2021-07-13 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210713_1549'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incidencia',
            options={'ordering': ('-fechaCreacion',)},
        ),
    ]
