# Generated by Django 2.2.10 on 2021-06-23 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextend',
            name='horasTrabajo',
            field=models.TimeField(blank=True),
        ),
    ]
